### ISSUE TITLE
Problem running from inside a NodeJs app inside a Docker container

### ISSUE THREAD

**Issue by Grumpier** [realies/audiowaveform-docker#10]
I've been struggling with this for a few days. I have a React/NodeJs app that calls audiowaveform to generate waveforms from user-supplied mp3 and wav files. Works great on a local Mac system. I have Dockerized my app and hoped to use your image from within the project container. Since your image is strictly command line based, I have tried using dockerode to issue a docker run to call realies/audiowaveform from within the container running my nodejs code. It seems that your image requires mount binding in order to get the output saved. Since I'm calling your image from inside a container, the bind is to a container volume that is in turn bound to the host via settings in docker-compose. When I run this I get a "mounts denied" error. Here's the call:

`  docker.run("realies/audiowaveform",  
    [`-i ${track.mp3Uri} -o 'test.png' -z auto -b 8 --background-color 00000000 --waveform-color 1976d2FF --axis-label-color FFFFFFFF --border-color 00000000 -h 50 -w 400`], 
    process.stdout,
    { WorkingDir: '/tmp',
      Hostconfig: {
        Binds: ['/music:/tmp']
      } 
    }
    )
` 

The exact error message is: "Mounts denied: The path /music is not shared from the host and is not known to Docker". 

Any suggestions would be much appreciated!

**Comment by realies** [comment]
@Grumpier, why are you trying to run a container within a container?

**Comment by Grumpier** [comment]
Thanks for getting back to me. I don’t know how else to communicate with your image. Any suggestions? Sent from my iPhoneOn 9 Mar 2023, at 21:14, realies ***@***.***> wrote:﻿
@Grumpier, why are you trying to run a container within a container?

**Comment by realies** [comment]
@Grumpier, any reason not to install the audiowaveform binary inside the container?

**Comment by Grumpier** [comment]
Yes, that’s the obvious solution, though I was hoping to keep the app as compartmentalized as possible and I’m a complete Docker newbie. Sent from my iPhoneOn 9 Mar 2023, at 21:48, realies ***@***.***> wrote:﻿
@Grumpier, any reason not to install the audiowaveform binary inside the container?

**Comment by realies** [comment]
Running a container inside a container is not optimal. If there's no reason to do so, you can install the audiowaveform binary inside the nodejs app container.

**Comment by Grumpier** [comment]
Yes, thanks. Any tips on the best way to ensure my nodejs app has access to the audiowave binary inside the container? Do I still call it with a child process as I would on a host system? Do I need to assign an ENTRYPOINT for the built binary? As I said, I’m a newbie. Sent from my iPhoneOn 10 Mar 2023, at 14:22, realies ***@***.***> wrote:﻿
Running a container inside a container is not optimal. If there's no reason to do so, you can install the audiowaveform binary inside the nodejs app container.

**Comment by realies** [comment]
Install the audiowaveform binary in the container or bake it into the image to be able to run it from within your nodejs app.

**Comment by Grumpier** [comment]
But how do I "bake it in"? If I modify my Dockerfile to something like this:

# syntax=docker/dockerfile:1

FROM realies/audiowaveform

FROM node:18-alpine 
WORKDIR /app
COPY ["package*.json", "./"]
COPY ./ ./
RUN npm i
CMD ["npm", "run", "start"]



audiowaveform is still not found in the shell. 

outlandaudiotrackssite-server-1  | /bin/sh: audiowaveform: not found

**Comment by realies** [comment]
```Dockerfile
FROM ubuntu:latest
RUN apt-get update && \
 apt-get install software-properties-common curl -y
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
 apt-get install -y nodejs
RUN add-apt-repository ppa:chris-needham/ppa && \
 apt-get update && \
 apt-get install audiowaveform -y
COPY ./app /app
WORKDIR /app
RUN npm i
CMD ["npm", "start"]

```
You can uninstall `software-properties-common` and `curl` after they are called. You can then use `audiowaveform` in node with something like:
```javascript
const util = require('util');
const exec = util.promisify(require('child_process').exec);
(async () => {
  console.log(await exec('audiowaveform --version'));
})();
```

You should have a look at more examples or read the docs: https://docs.docker.com/reference/; https://nodejs.org/api/child_process.html

**Comment by Grumpier** [comment]
Thanks! I’ll check this out. Sent from my iPhoneOn 10 Mar 2023, at 20:58, realies ***@***.***> wrote:﻿
FROM ubuntu:latest
RUN apt-get update && \
 apt-get install software-properties-common curl -y
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
 apt-get install -y nodejs
RUN add-apt-repository ppa:chris-needham/ppa && \
 apt-get update && \
 apt-get install audiowaveform -y
COPY ./app /app
WORKDIR /app
RUN npm i
CMD ["npm", "start"]

You can uninstall software-properties-common and curl after they are called. You can then use audiowaveform in node with something like:
const util = require('util');
const exec = util.promisify(require('child_process').exec);
(async () => {
  console.log(await exec('audiowaveform --version'));
})();
You should have a look at more examples or read the docs: https://docs.docker.com/reference/; https://nodejs.org/api/child_process.html

**Comment by Grumpier** [comment]
Your additions to my Dockerfile worked perfectly. Thanks. I didn’t realize you can just apt-get install node into ubuntu. Duh!Sent from my iPhoneOn 10 Mar 2023, at 20:58, realies ***@***.***> wrote:﻿
FROM ubuntu:latest
RUN apt-get update && \
 apt-get install software-properties-common curl -y
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
 apt-get install -y nodejs
RUN add-apt-repository ppa:chris-needham/ppa && \
 apt-get update && \
 apt-get install audiowaveform -y
COPY ./app /app
WORKDIR /app
RUN npm i
CMD ["npm", "start"]

You can uninstall software-properties-common and curl after they are called. You can then use audiowaveform in node with something like:
const util = require('util');
const exec = util.promisify(require('child_process').exec);
(async () => {
  console.log(await exec('audiowaveform --version'));
})();
You should have a look at more examples or read the docs: https://docs.docker.com/reference/; https://nodejs.org/api/child_process.html
