### ISSUE TITLE
Create version tags instead tagging all images as `latest`

### ISSUE THREAD

**Issue by sarayourfriend** [realies/audiowaveform-docker#11]
It's currently not possible to pin to a version of this image due to the publishing process always tagging to only `latest` without any new version tag. We've [run into an issue using this image over on Openverse](https://github.com/WordPress/openverse/discussions/2412) that would be solved by having version-specific tags rather than only the `latest` tag.

If there aren't clear versions to use, at the very least date-versioned tags would be helpful, like `2023-10-02` for the most recent `latest`.

**Comment by realies** [comment]
https://github.com/realies/audiowaveform-docker/commit/71f2adc06e887de6ea52be8d69eb7a5c2a822910 is now releasing tagged commits on https://github.com/bbc/audiowaveform with their respective image tag.
