### ISSUE TITLE
Dockerfile fails to build with alpine:latest

### ISSUE THREAD

**Issue by eroo36** [realies/audiowaveform-docker#6]
I was not able to build this again after the last alpine update(3.16). Changing the first line in the Dockerfile with `FROM alpine:3.14 from builder` fixes the building issue. It might also work with newer version alpine 3.15 but did not test it.

**Comment by realies** [comment]
@eroo36, just migrated the image to `alpine:edge` in [c087556](https://github.com/realies/audiowaveform-docker/commit/c087556f1fef9b251b19a9b11a383c5e6d99b786). The new Dockerfile should work with `alpine:latest`. Let me know if there are any issues, can look into pushing more tags (like stable) if there's a demand for it too.
